name: "gb200-fp4-1p1d"

model:
  path: "dsfp4"
  container: "0.5.5.post2"
  precision: "fp4"

resources:
  gpu_type: "gb200"
  agg_nodes: 1
  agg_workers: 1
  gpus_per_node: 4

sweep:
  ep-size: [1, 4]

backend:

  prefill_environment:
    TORCH_DISTRIBUTED_DEFAULT_TIMEOUT: "1800"
    PYTHONUNBUFFERED: "1"
    DYN_SKIP_SGLANG_LOG_FORMATTING: "1"
    SGLANG_NVFP4_CKPT_FP8_GEMM_IN_ATTN: "1"
    SGLANG_PER_TOKEN_GROUP_QUANT_8BIT_V2: "1"
    SGLANG_DISAGGREGATION_HEARTBEAT_MAX_FAILURE: "100000"
    SGLANG_DISAGGREGATION_BOOTSTRAP_TIMEOUT: "100000"
    SGLANG_DISAGGREGATION_WAITING_TIMEOUT: "100000"
    SGLANG_HACK_SEQ_BOOTSTRAP_ROOM: "1"
    MC_TE_METRIC: "true"
    MC_FORCE_MNNVL: "1"
    NCCL_MNNVL_ENABLE: "1"
    NCCL_CUMEM_ENABLE: "1"
    SGLANG_MOONCAKE_CUSTOM_MEM_POOL: "True"
    SGLANG_USE_MESSAGE_QUEUE_BROADCASTER: "0"
    SGLANG_DISABLE_TP_MEMORY_INBALANCE_CHECK: "1"
    SGLANG_FLASHINFER_FP4_GEMM_BACKEND: "trtllm" # this might be a bit faster

  decode_environment:
    TORCH_DISTRIBUTED_DEFAULT_TIMEOUT: "1800"
    PYTHONUNBUFFERED: "1"
    DYN_SKIP_SGLANG_LOG_FORMATTING: "1"
    SGLANG_NVFP4_CKPT_FP8_GEMM_IN_ATTN: "1"
    SGLANG_PER_TOKEN_GROUP_QUANT_8BIT_V2: "1"
    SGLANG_DISAGGREGATION_HEARTBEAT_MAX_FAILURE: "100000"
    SGLANG_DISAGGREGATION_BOOTSTRAP_TIMEOUT: "100000"
    SGLANG_DISAGGREGATION_WAITING_TIMEOUT: "100000"
    SGLANG_HACK_SEQ_BOOTSTRAP_ROOM: "1"
    MC_TE_METRIC: "true"
    MC_FORCE_MNNVL: "1"
    NCCL_MNNVL_ENABLE: "1"
    NCCL_CUMEM_ENABLE: "1"
    SGLANG_MOONCAKE_CUSTOM_MEM_POOL: "True"
    SGLANG_USE_MESSAGE_QUEUE_BROADCASTER: "0"
    SGLANG_DISABLE_TP_MEMORY_INBALANCE_CHECK: "1"
    SGLANG_FLASHINFER_FP4_GEMM_BACKEND: "trtllm" # this might be a bit faster

  sglang_config:
    prefill:
      disaggregation-mode: "prefill"
      served-model-name: "deepseek-ai/DeepSeek-R1"
      model-path: "/model/"
      trust-remote-code: true
      disable-radix-cache: true
      kv-cache-dtype: "fp8_e4m3"
      attention-backend: "trtllm_mla"
      quantization: "modelopt_fp4"
      moe-runner-backend: "flashinfer_trtllm"
      stream-interval: 10
      watchdog-timeout: 1000000
      context-length: 2200
      mem-fraction-static: 0.90
      max-total-tokens: 8192
      chunked-prefill-size: 8192
      cuda-graph-max-bs: 128
      max-running-requests: 512
      scheduler-recv-interval: 10
      enable-flashinfer-allreduce-fusion: true
      enable-symm-mem: true
      moe-dense-tp-size: 1
      tensor-parallel-size: 4
      expert-parallel-size: "{ep-size}"

    decode:
      disaggregation-mode: "decode"
      served-model-name: "deepseek-ai/DeepSeek-R1"
      model-path: "/model/"
      trust-remote-code: true
      disable-radix-cache: true
      kv-cache-dtype: "fp8_e4m3"
      attention-backend: "trtllm_mla"
      quantization: "modelopt_fp4"
      moe-runner-backend: "flashinfer_trtllm"
      stream-interval: 10
      watchdog-timeout: 1000000
      context-length: 2200
      mem-fraction-static: 0.90
      max-total-tokens: 8192
      chunked-prefill-size: 8192
      cuda-graph-max-bs: 128
      max-running-requests: 512
      scheduler-recv-interval: 10
      enable-flashinfer-allreduce-fusion: true
      enable-symm-mem: true
      moe-dense-tp-size: 1
      tensor-parallel-size: 4
      expert-parallel-size: "{ep-size}"

benchmark:
  type: "sa-bench"
  isl: 1024
  osl: 1024
  concurrencies: "4x8x32x64x128x256x512x1024"
  req_rate: "inf"